<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="User-PC" name="com.orangehrm.test.LoginTest" tests="6" failures="1" timestamp="15 Mar 2019 09:56:58 GMT" time="135.702" errors="0">
  <testcase name="verifyLoginWithInvalidPasssword" time="41.176" classname="com.orangehrm.test.LoginTest"/>
  <testcase name="loginSuccesfull" time="20.908" classname="com.orangehrm.test.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [Welcome] but found [Welcome Admin]">
      <![CDATA[java.lang.AssertionError: expected [Welcome] but found [Welcome Admin]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.orangehrm.page.HomePage.isHomePageLoaded(HomePage.java:34)
at com.orangehrm.test.LoginTest.loginSuccesfull(LoginTest.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginSuccesfull -->
  <testcase name="verifySocialMediaLink" time="46.417" classname="com.orangehrm.test.LoginTest"/>
  <testcase name="verifyLoginBlankUsername" time="8.442" classname="com.orangehrm.test.LoginTest"/>
  <testcase name="verifyDefaultCursorFocus" time="8.539" classname="com.orangehrm.test.LoginTest"/>
  <testcase name="verifyLoginWithInvalidUsername" time="10.220" classname="com.orangehrm.test.LoginTest"/>
</testsuite> <!-- com.orangehrm.test.LoginTest -->
